Add a publish workflow to github actions
radio-astro-tools/radio-beam pull request #93
Opened 2021-03-18 17:14 UTC by e-koch

We should make wheels in the release. I grabbed @astrofrog's publish workflow from https://github.com/radio-astro-tools/casa-formats-io

2021-03-18 18:27 UTC, keflavich commented
lgtm, should we get @astrofrog's review before merging or go ahead?

2021-03-18 19:31 UTC, astrofrog commented
Are there C extensions in radio-beam? If not we could build universal wheels, I can show how if needed.

2021-03-18 19:50 UTC, e-koch commented
@astrofrog There's no C extension (yet). Guidance on building universal wheels would be much appreciated!

2021-03-18 19:56 UTC, astrofrog requested changes
I think the changes below would work to build a pure Python wheel

2021-03-18 19:56 UTC, astrofrog commented on .github/workflows/publish.yml
> +      #  run: python -m pip install cibuildwheel
Maybe remove these last two commented lines because that's not the only thing that will change

2021-03-18 19:56 UTC, astrofrog commented on .github/workflows/publish.yml
> +        run: python -m build --sdist --outdir dist/ .
```suggestion
        run: python -m build --sdist --wheel --outdir dist/ .
```

2021-03-18 19:56 UTC, astrofrog commented on .github/workflows/publish.yml
> +          path: dist/*.tar.gz
```suggestion
          path: dist/*
```

2021-03-18 19:56 UTC, astrofrog commented on .github/workflows/publish.yml
> +  build_sdist:
The wheel can easily be built in this section:

```suggestion
  build_sdist_and_wheel:
```

2021-03-18 19:56 UTC, astrofrog commented on .github/workflows/publish.yml
> +  build_wheels:
Remove this ``build_wheels`` section

2021-03-19 14:40 UTC, e-koch commented
@astrofrog, @keflavich -- I think this is good to merge now. Pypi upload is set up for the repo, too.

2021-03-19 16:05 UTC, merged